In [1]:
import numpy as np

In [2]:
#array creating
arr1d=np.array([1,2,3,4,5,6])
arr1d
print(arr1d)

[1 2 3 4 5 6]


In [3]:
arr1d.dtype

dtype('int32')

In [4]:
type(arr1d)

numpy.ndarray

In [5]:
#array ka dimension pta karne ke liye
arr1d.ndim

1

In [6]:
arr2d=np.array([[1,2,3,4],[4,5,6,7]])
arr2d
print(arr2d)

[[1 2 3 4]
 [4 5 6 7]]


In [7]:
type(arr2d)

numpy.ndarray

In [8]:
arr2d.ndim

2

In [9]:
arr2d.size

8

In [10]:
arr2d.shape

(2, 4)

In [11]:
#2=row 4=column

In [12]:
arr2d.dtype

dtype('int32')

In [13]:
#ones matrix array(2d)
arr1=np.array([[1,1,1],[1,1,1],[1,1,1]])
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
#once matrix create karne ke liye function
arr2=np.ones(5)
arr2

array([1., 1., 1., 1., 1.])

In [15]:
arr2.dtype

dtype('float64')

In [16]:
type(arr2)

numpy.ndarray

In [17]:
#ones matrix by default float value deta hai

In [18]:
arr2=np.ones((4,4),dtype=int)
arr2

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
#zeros matrix

In [20]:
arr3=np.zeros((5,5))
arr3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
arr3=np.zeros((5,5),dtype=int)
arr3

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
arr3=np.zeros((5,5),dtype=str)
arr3

array([['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', ''],
       ['', '', '', '', '']], dtype='<U1')

In [23]:
arr3=np.zeros((5,5))
print(arr3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 

In [24]:
arr4=np.empty((3,4))
arr4

array([[1.50708349e-312, 0.00000000e+000, 8.76794447e+252,
        2.15895723e+227],
       [6.48224638e+170, 3.67145870e+228, 9.92154585e-096,
        9.03292329e+271],
       [9.08366793e+223, 1.41075687e+232, 1.16070543e-028,
        4.67294031e-307]])

# numpy function

# arange()

In [25]:
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [26]:
#np.arange(star,ende,steps)

array_1d=np.arange(1,13)
print(array_1d)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
#agar hme 1 se 12 ke bich me har dusri value chahiye
a=np.arange(1,13,2)
print(a)

[ 1  3  5  7  9 11]


# inspace()

In [31]:
#randam value deta hai
np.linespace()

AttributeError: module 'numpy' has no attribute 'linespace'

# reshape()

# raval()